### ISSUE TITLE
依赖还有pip3 install dnspython

### ISSUE THREAD

**Issue by HA-JD** [UzJu/Cloud-Bucket-Leak-Detection-Tools#6]

**Comment by UzJu** [comment]
好滴 谢谢师傅的提醒

**Comment by ldz0** [comment]
`git clone https://github.com/rthalley/dnspython
cd dnspython/
python setup.py install`

**Comment by ldz0** [comment]
`git clone https://github.com/rthalley/dnspython`
`cd dnspython/`
`python setup.py install`
