### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by qiuluo-oss** [UzJu/Cloud-Bucket-Leak-Detection-Tools#7]
![image](https://user-images.githubusercontent.com/72497146/176367604-c5d5d407-6208-4880-aea7-d3e39bc7611b.png)

**Comment by UzJu** [comment]
What orders caused the problem

**Comment by UzJu** [comment]
Please take a screenshot of the complete stack error screenshot thanks

**Comment by qiuluo-oss** [comment]
python3 main.py -f aliyun url.txt

**Comment by UzJu** [comment]
Fix: https://github.com/UzJu/Cloud-Bucket-Leak-Detection-Tools/commit/1445d0b44598ead99ef01b4bce6394585b9f1a30
