### ISSUE TITLE
腾讯云COS模块运作不起来,老是说缺少urlparse

### ISSUE THREAD

**Issue by Gametasd** [UzJu/Cloud-Bucket-Leak-Detection-Tools#8]
在requirements安装完之后
![图片](https://user-images.githubusercontent.com/32217917/181837742-91bca9ee-d2f2-4940-9c0a-cac468c9131d.png)
一直不起来，自己也尝试修改了一下，也还是运作不起来，很奇怪

**Comment by Gametasd** [comment]
我也安装了cos-python-sdk-v5模块

**Comment by Gametasd** [comment]
requirements是正常安装完的

**Comment by Gametasd** [comment]
换了qcloud3就可以了

**Comment by Gametasd** [comment]
师傅，这个的话，我修好了，qcloud支持的是py2的emmm，所以我去github上找了一位老哥开源的支持py3的qcloud然后把import改一下就ok了，华为云的obs可能需要还需要安装一下esdk-obs-python库才可以正常使用

**Comment by liao545** [comment]
> 师傅，这个的话，我修好了，qcloud支持的是py2的emmm，所以我去github上找了一位老哥开源的支持py3的qcloud然后把import改一下就ok了，华为云的obs可能需要还需要安装一下esdk-obs-python库才可以正常使用
师傅怎么改的，麻烦教教我

**Comment by liao545** [comment]
我也找到了，感谢提示

**Comment by Gametasd** [comment]
> > 师傅，这个的话，我修好了，qcloud支持的是py2的emmm，所以我去github上找了一位老哥开源的支持py3的qcloud然后把import改一下就ok了，华为云的obs可能需要还需要安装一下esdk-obs-python库才可以正常使用
> > 师傅怎么改的，麻烦教教我

就直接在github上找到这个包，然后放在Python的那个放包的地方，叫啥我忘了，就是qcloud的那个地方，然后放进去import改为3就行了

**Comment by UzJu** [comment]
不好意思 最近有些忙 没怎么看Github 感谢您的提问与分享。

**Comment by UzJu** [comment]
师傅可以试试pip3 install cos-python-sdk-v5 目前测试是可以解决的

**Comment by z7701858** [comment]
> 师傅可以试试pip3 install cos-python-sdk-v5 目前测试是可以解决的
Collecting qcloud-cos
  Using cached qcloud_cos-3.3.6.tar.gz (10 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-mujijnzd/qcloud-cos/setup.py'"'"'; __file__='"'"'/tmp/pip-install-mujijnzd/qcloud-cos/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-mujijnzd/qcloud-cos/pip-egg-info
         cwd: /tmp/pip-install-mujijnzd/qcloud-cos/
    Complete output (1 lines):
    Sorry, only python 2.6 or 2.7 is supported
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

大佬看看？

**Comment by UzJu** [comment]
@z7701858 python版本是多少

**Comment by PolarPeak** [comment]
我3.9.8也是同样报错，直接把Cloud-Bucket-Leak-Detection-Tools-0.4.0\core\tencent\cos.py单独拿出来用了

**Comment by UzJu** [comment]
@PolarPeak 这个我再检查一下
